### ISSUE TITLE
[BUG]: Write Permission Issue

### ISSUE THREAD

**Issue by AmulyaChaya** [dell/dellemc-openmanage-ansible-modules#585] opened 2023-11-23 08:34 UTC
### Bug Description

I'm using idrac_os_deployment module for os deployment. 
I'm using http protocol and keeping custom kickstart file and raw RHEL 8 ISO image in that. 
Playbook is running successfully till copy ks to extracted task. After that I'm getting permission issue when trying to append ks path to the linux boot menu.
![MicrosoftTeams-image (8)](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/18027747/c5ec7897-1ab7-4011-a859-708aacfde78d)
![MicrosoftTeams-image (11)](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/18027747/1d904f30-15f8-4c35-8a6c-b0ccfa1f57d0)

### Component or Module Name

idrac_os_deployment

### Ansible Version

2.13.8

### Python Version

3.19.

### iDRAC/OME/OME-M version

IDRAC 9
OME 4

### Operating System

RHEL 8

### Playbook Used

---
- hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - vars_files/input_var.yml
    - vars_files/ome_idrac_cred.yml
    - vars_files/osd.yml
  roles:
    - dellemc.openmanage.idrac_os_deployment

### Logs

fatal: [localhost]: FAILED! => {
    "failed_when_result": true,
    "idrac_os_deployment_failure": {
        "changed": false,
        "failed": true,
        "failed_task_name": "Append ks path to the linux boot menu",
        "msg": "One or more items failed",
        "results": [
            {
                "ansible_loop_var": "item",
                "changed": false,
                "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload__r22i2xu/ansible_ansible.builtin.lineinfile_payload.zip/ansible/module_utils/basic.py\", line 1692, in atomic_move\n    os.rename(b_src, b_dest)\nOSError: [Errno 18] Invalid cross-device link: b'/home/hna/.ansible/tmp/ansible-tmp-1700726535.893579-1039405-100383543449893/tmpyw_73xcn' -> b'/tmp/omam_osd3bue160h/extract/isolinux/isolinux.cfg'\n",
                "failed": true,
                "invocation": {
                    "module_args": {
                        "attributes": null,
                        "backrefs": true,
                        "backup": false,
                        "create": false,
                        "firstmatch": true,
                        "group": null,
                        "insertafter": null,
                        "insertbefore": null,
                        "line": [\\1 inst.ks=cdrom:/ks.cfg](file://1%20inst.ks=cdrom:/ks.cfg),
                        "mode": null,
                        "owner": null,
                        "path": "/tmp/omam_osd3bue160h/extract/isolinux/isolinux.cfg",
                        "regexp": "^(.*inst.stage2=hd:LABEL.*?)( inst.ks=cdrom:/ks.cfg)?$",
                        "search_string": null,
                        "selevel": null,
                        "serole": null,
                        "setype": null,
                        "seuser": null,
                        "state": "present",
                        "unsafe_writes": false,
                        "validate": null
                    }
                },
                "item": "/tmp/omam_osd3bue160h/extract/isolinux/isolinux.cfg",
                "msg": "The destination directory (/tmp/omam_osd3bue160h/extract/isolinux) is not writable by the current user. Error was: [Errno 13] Permission denied: b'/tmp/omam_osd3bue160h/extract/isolinux/.ansible_tmps_frkdueisolinux.cfg'"
            },
            {
                "ansible_loop_var": "item",
                "changed": false,
                "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_nq0vaytm/ansible_ansible.builtin.lineinfile_payload.zip/ansible/module_utils/basic.py\", line 1692, in atomic_move\n    os.rename(b_src, b_dest)\nOSError: [Errno 18] Invalid cross-device link: b'/home/hna/.ansible/tmp/ansible-tmp-1700726536.3021898-1039405-170472215686523/tmpqtchw33w' -> b'/tmp/omam_osd3bue160h/extract/EFI/BOOT/grub.cfg'\n",
                "failed": true,
                "invocation": {
                    "module_args": {
                        "attributes": null,
                        "backrefs": true,
                        "backup": false,
                        "create": false,
                        "firstmatch": true,
                        "group": null,
                        "insertafter": null,
                        "insertbefore": null,
                        "line": [\\1 inst.ks=cdrom:/ks.cfg](file://1%20inst.ks=cdrom:/ks.cfg),
                        "mode": null,
                        "owner": null,
                        "path": "/tmp/omam_osd3bue160h/extract/EFI/BOOT/grub.cfg",
                        "regexp": "^(.*inst.stage2=hd:LABEL.*?)( inst.ks=cdrom:/ks.cfg)?$",
                        "search_string": null,
                        "selevel": null,
                        "serole": null,
                        "setype": null,
                        "seuser": null,
                        "state": "present",
                        "unsafe_writes": false,
                        "validate": null
                    }
                },
                "item": "/tmp/omam_osd3bue160h/extract/EFI/BOOT/grub.cfg",
                "msg": "The destination directory (/tmp/omam_osd3bue160h/extract/EFI/BOOT) is not writable by the current user. Error was: [Errno 13] Permission denied: b'/tmp/omam_osd3bue160h/extract/EFI/BOOT/.ansible_tmp68men0mygrub.cfg'"
            }
        ],
        "skipped": false
    }
}

### Steps to Reproduce

---
- hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - vars_files/input_var.yml
    - vars_files/ome_idrac_cred.yml
    - vars_files/osd.yml
  roles:
    - dellemc.openmanage.idrac_os_deployment

os_name: rhel
os_version: 8
hostname: 10.2.3.4
username: root
password: 123
validate_certs: true
source:
  protocol: "http"
  iso_path: /
  iso_name: rhel-8.0-x86_64-dvd.iso
  ks_path:  /ks.cfg
  hostname: host1
  username: 123
  password: 111
destination:
  protocol: "http"
  hostname: "host1"
  username: 123
  password: tyhh
  iso_path: /
  mountpoint: /
wait_for_os_deployment: true
os_deployment_timeout: 120
eject_iso: true
delete_custom_iso: true

### Expected Behavior

Run the playbook with role

### Actual Behavior

Failing to write operation when attaching ks path in /tmp folder

### Screenshots

![MicrosoftTeams-image (11)](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/18027747/660d6a62-dfbc-4a0c-98ac-bd483f122c2c)
![MicrosoftTeams-image (8)](https://github.com/dell/dellemc-openmanage-ansible-modules/assets/18027747/ba47ddf0-c0c2-451a-9b08-095d238a09cd)

**Comment by sachin-apa** [comment] 2023-11-27 02:55
@AmulyaChaya this is a duplicate of the issue #514. please try the fix or wait for the release 8.5.0 (Nov 30 2023).
closing this issue for now, please reopen if the issue is not resolved.

**Closed as completed** 2023-11-27 02:56 UTC
Labels: type/bug, needs-triage
