### ISSUE TITLE
Not able to work with dellmc-openmange ansible-modules

### ISSUE THREAD

**Issue by vchevakula** [dell/dellemc-openmanage-ansible-modules#52] opened 2019-06-02 05:15 UTC
Hello All,

I'm first using this dellemc-openmanage-ansible-modules .
I have configured my virtual environment  in pycharm as dell-scripts. Installed ansible 2.8,  pip and installed omsdk by following this below article
https://github.com/dell/omsdk
Then installed dell open managed ansible module
https://github.com/dell/dellemc-openmanage-ansible-modules
`(dell-scripts) victorCS:dell-scripts vchevakula$ ansible --version
ansible 2.8.0
  config file = None
  configured module search path = [u'/Users/vchevakula/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/vchevakula/.virtualenvs/dell-scripts/lib/python2.7/site-packages/ansible
  executable location = /Users/vchevakula/.virtualenvs/dell-scripts/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
(dell-scripts) victorCS:dell-scripts vchevakula$ 
`
According documentation I have configured inventory file as below 
`[all]
192.168.10.10 host='192.168.10.10' user='root' pwd='calvin'`

playbook 
`---
- hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: ~/.virtualenvs/dell-scripts/bin/python2.7

  tasks:
    - name: Get hardware inventory
      dellemc_get_system_inventory:
        idrac_ip: "{{ host }}"
        idrac_user: "{{ user }}"
        idrac_pwd: "{{ pwd }}"`

I'm getting the output as below 
`(dell-scripts) victorCS:dell-scripts vchevakula$ ~/.virtualenvs/dell-scripts/bin/ansible-playbook playbook.yml -i inventory -vvv 
ansible-playbook 2.8.0
  config file = None
  configured module search path = [u'/Users/vchevakula/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/vchevakula/.virtualenvs/dell-scripts/lib/python2.7/site-packages/ansible
  executable location = /Users/vchevakula/.virtualenvs/dell-scripts/bin/ansible-playbook
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
No config file found; using defaults
host_list declined parsing /Users/vchevakula/PycharmProjects/dell-scripts/inventory as it did not pass it's verify_file() method
script declined parsing /Users/vchevakula/PycharmProjects/dell-scripts/inventory as it did not pass it's verify_file() method
auto declined parsing /Users/vchevakula/PycharmProjects/dell-scripts/inventory as it did not pass it's verify_file() method
Parsed /Users/vchevakula/PycharmProjects/dell-scripts/inventory inventory source with ini plugin

PLAYBOOK: playbook.yml ********************************************************************************************************************
1 plays in playbook.yml

PLAY [all] ********************************************************************************************************************************
META: ran handlers

TASK [Get hardware inventory] *************************************************************************************************************
task path: /Users/vchevakula/PycharmProjects/dell-scripts/playbook.yml:8
<192.168.10.10> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.10.10> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/vchevakula/.ansible/cp/e418d7e50a 192.168.192.126 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.10.10> (255, '', 'root@192.168.10.10: Permission denied (publickey,password).\r\n')
fatal: [192.168.192.126]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: root@192.168.192.126: Permission denied (publickey,password).", 
    "unreachable": true
}

PLAY RECAP ********************************************************************************************************************************
192.168.10.10            : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

`

I have prepared those files as shown in the documentations.

https://github.com/dell/dellemc-openmanage-ansible-modules/blob/devel/guides/OMAM_2.0_Users_Guide.pdf 

Can anyone guide if I'm making any mistake

**Comment by anupamaloke** [comment] 2019-06-03 08:48
@vchevakula, OpenManage Ansible modules use iDRAC REST APIs, so the modules need to be locally on the ansible controller. You can do that by using either of the following methods :
- **Using playbook header**
```yaml
- host:  all
  connection: local
```
- **Use ```delegate_to``` in your playbook**
```yaml
task:
- name: Get hardware inventory
  dellemc_get_system_inventory:
    idrac_ip: "{{ host }}"
    idrac_user: "{{ user }}"
    idrac_pwd: "{{ pwd }}"
  delegate_to:  localhost
```
- **Using Ansible command-line**
```
ansible-playbook --connection=local 127.0.0.1 playbook.yml
```
- **Using inventory**
```ini
[all]
192.168.10.10 host='192.168.10.10' user='root' pwd='calvin'  ansible_connection=local
```
- **Using Ansible configuration file ansible.cfg**
```ini
[defaults]
transport = local
```
I would suggest using the first or second option in your playbook.

**Comment by vchevakula** [comment] 2019-06-03 18:40
Hello @anupamaloke,

Thanks for your input. I tried all the options and I'm getting this below  error. Please let me know if I'm missing anything. I just did follow the documentation
```
(dell-scripts) vijayaCS:dell-scripts vchevakula$ ansible-playbook --connection=local playbook.yml -i inventory

PLAY [all] ********************************************************************************************************************************************************************************

TASK [Get hardware inventory] *************************************************************************************************************************************************************
fatal: [192.168.192.126]: FAILED! => {"msg": "module (dellemc_get_system_inventory) is missing interpreter line"}

PLAY RECAP ********************************************************************************************************************************************************************************
192.168.10.10            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(dell-scripts) vijayaCS:dell-scripts vchevakula$ 
```

**Comment by anupamaloke** [comment] 2019-06-12 08:08
@vchevakula, I am guessing that the issue is due to some ansible module path issue. Can you post the output of the "ansible-playbook -vvvv  --connection=local playbook.yml -i inventory"?

**Comment by rajeevarakkal** [comment] 2019-11-21 10:18
@vchevakula Closing this issue since there is no update since long

**Closed by rajeevarakkal** 2019-11-21 10:18 UTC
