### ISSUE TITLE
ome_firmware_baseline_compliance_info API limit

### ISSUE THREAD

**Issue by mrhollywoodgates** [dell/dellemc-openmanage-ansible-modules#171] opened 2020-11-05 16:36 UTC
When using ome_firmware_baseline_compliance_info with the `baseline_name` option, the query only returns the top 100 results from the baseline report, instead of all the results. 

This seems to be a result of the url: 

baselines_compliance_report_path = "UpdateService/Baselines({Id})/DeviceComplianceReports"

which defaults to 100 responses. 

Using: 
baselines_compliance_report_path = "UpdateService/Baselines({Id})/DeviceComplianceReports?$top=1000"

would return the top 1000 responses. 

This could be parameterized, or simply increased in the module.

**Comment by grantcurell** [comment] 2021-01-27 19:49
@anupamaloke I'd be willing to take this one. I think I know what the problem is

**Comment by jagadeeshnv** [comment] 2021-02-25 09:27
@mrhollywoodgates This has been fixed with the latest release 3.1.0. Kindly Verify

**Comment by jagadeeshnv** [comment] 2021-03-23 11:59
@mrhollywoodgates Hope this is working fine with the latest

**Closed** 2021-04-29 07:11 UTC
Labels: enhancement
