### ISSUE TITLE
pysnmp issues dell getfirmware

### ISSUE THREAD

**Issue by kumaresan078** [dell/dellemc-openmanage-ansible-modules#14] opened 2018-11-13 05:28 UTC
Hi,

I am trying to run getfirmwareinventory.yml had below issues.Can someone help to fix it?

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'noValue'
fatal: [172.21.35.235]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NQzfD_/ansible_module_dellemc_get_firmware_inventory.py\", line 18, in <module>\n    from ansible.module_utils.dellemc_idrac import *\n  File \"/tmp/ansible_NQzfD_/ansible_modlib.zip/ansible/module_utils/dellemc_idrac.py\", line 21, in <module>\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkcreds.py\", line 27, in <module>\n    from omsdk.sdkprint import PrettyPrint\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkprint.py\", line 44, in <module>\n    from pysnmp.hlapi import *\n  File \"/usr/lib/python2.7/site-packages/pysnmp/hlapi/__init__.py\", line 7, in <module>\n    from pysnmp.proto.rfc1902 import *\n  File \"/usr/lib/python2.7/site-packages/pysnmp/proto/rfc1902.py\", line 9, in <module>\n    from pysnmp.proto import rfc1155, error\n  File \"/usr/lib/python2.7/site-packages/pysnmp/proto/rfc1155.py\", line 50, in <module>\n    class NetworkAddress(univ.Choice):\n  File \"/usr/lib/python2.7/site-packages/pysnmp/proto/rfc1155.py\", line 55, in NetworkAddress\n    def clone(self, value=univ.noValue, **kwargs):\nAttributeError: 'module' object has no attribute 'noValue'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by rajshekarp87** [comment] 2018-11-13 07:35
Hi Kumaresan,

Thanks for trying out Dell EMC OpenManage Ansible Modules. Can you please share below details to root cause the issue better.

- Dell EMC OpenManage Ansible Modules version
- OMSDK version
- Python, PIP and PySNMP version
- Playbook

Thanks & Regards,
Rajshekar P

**Comment by kumaresan078** [comment] 2018-11-13 09:16
Hi,

Please find below details.

Dell EMC OpenManage Ansible Modules version - 1.1
OMSDK version - 1.2
Python - Python 2.7.5
PIP - pip 18.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)
pysnmp==4.4.6
    
Playbook:

---
- hosts: all
  connection: local
  name: Get Installed Firmware Inventory
  gather_facts: False

  tasks:
  - name: Get Installed Firmware Inventory
    dellemc_get_firmware_inventory:
       idrac_ip:        "192.168.35.235"
       idrac_user:      "admin"
       idrac_pwd:       "calvin"

Regards
Kumaresan

**Comment by rajshekarp87** [comment] 2018-11-14 14:53
Hi Kumaresan,

Thanks for sharing required details. Your playbook and other details are proper. We tried reproducing the issue with playbook shared by you. It works fine and issue is not reproachable.

Could you please let us if you are still hitting with the issue.

Thanks & Regards,
Rajshekar P

**Comment by kumaresan078** [comment] 2018-11-21 17:11
Hi Rajshekar,

Thanks for the update.I have completely installed all the modules on another machine from scratch it works well.

Have another query? We have dell openmanage installed on windows machine through which we update firmware for all dell servers.Is there way to integrate dell openmanage ansible module with that?

Other query dell emc module supports only power generation 12 & above we have power generation 11 servers in our environment is there any module that support?

Regards
kumaresan

**Comment by rajshekarp87** [comment] 2018-11-28 02:52
Hi Kumaresan,

Glad to hear that the issue is resolved.

Dell EMC OpenManage Ansible Modules cannot be integrated with any of the Dell EMC OpenManage products and we do not have modules that support PowerEdge 11G Servers.

Thanks & Regards,
Rajshekar P

**Comment by DanielFroehlich** [comment] 2018-12-06 14:17
> Thanks for sharing required details. Your playbook and other details are proper. We tried reproducing the issue with playbook shared by you. It works fine and issue is not reproducible.
I had the same issue - see  issue #23 . Can be fixed with 
`pip install pyasn1 --upgrade 
`

**Comment by rajeevarakkal** [comment] 2019-06-20 04:06
closing this issue

**Closed by rajeevarakkal** 2019-06-20 04:06 UTC
